-- White Room Kid Kiyotaka - City ranged-strike adaptation dummy buildings
-- Invisible per-city buildings applied by Lua when White Room cities fire.

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description)
VALUES
('BUILDINGCLASS_WR_CITY_RANGE_ADAPT_1',  'BUILDING_WR_CITY_RANGE_ADAPT_1',  'TXT_KEY_BUILDING_WR_CITY_RANGE_ADAPT'),
('BUILDINGCLASS_WR_CITY_RANGE_ADAPT_5',  'BUILDING_WR_CITY_RANGE_ADAPT_5',  'TXT_KEY_BUILDING_WR_CITY_RANGE_ADAPT'),
('BUILDINGCLASS_WR_CITY_RANGE_ADAPT_10', 'BUILDING_WR_CITY_RANGE_ADAPT_10', 'TXT_KEY_BUILDING_WR_CITY_RANGE_ADAPT'),
('BUILDINGCLASS_WR_CITY_RANGE_ADAPT_25', 'BUILDING_WR_CITY_RANGE_ADAPT_25', 'TXT_KEY_BUILDING_WR_CITY_RANGE_ADAPT'),
('BUILDINGCLASS_WR_CITY_RANGE_ADAPT_50', 'BUILDING_WR_CITY_RANGE_ADAPT_50', 'TXT_KEY_BUILDING_WR_CITY_RANGE_ADAPT');

INSERT INTO Buildings
    (Type, BuildingClass, Cost, FaithCost, GreatWorkCount, PrereqTech, Description, NeverCapture,
     NukeImmune, HurryCostModifier, RangedStrikeModifier)
VALUES
('BUILDING_WR_CITY_RANGE_ADAPT_1',  'BUILDINGCLASS_WR_CITY_RANGE_ADAPT_1',  -1, -1, -1, NULL, 'TXT_KEY_BUILDING_WR_CITY_RANGE_ADAPT', 1, 1, -1, 1),
('BUILDING_WR_CITY_RANGE_ADAPT_5',  'BUILDINGCLASS_WR_CITY_RANGE_ADAPT_5',  -1, -1, -1, NULL, 'TXT_KEY_BUILDING_WR_CITY_RANGE_ADAPT', 1, 1, -1, 5),
('BUILDING_WR_CITY_RANGE_ADAPT_10', 'BUILDINGCLASS_WR_CITY_RANGE_ADAPT_10', -1, -1, -1, NULL, 'TXT_KEY_BUILDING_WR_CITY_RANGE_ADAPT', 1, 1, -1, 10),
('BUILDING_WR_CITY_RANGE_ADAPT_25', 'BUILDINGCLASS_WR_CITY_RANGE_ADAPT_25', -1, -1, -1, NULL, 'TXT_KEY_BUILDING_WR_CITY_RANGE_ADAPT', 1, 1, -1, 25),
('BUILDING_WR_CITY_RANGE_ADAPT_50', 'BUILDINGCLASS_WR_CITY_RANGE_ADAPT_50', -1, -1, -1, NULL, 'TXT_KEY_BUILDING_WR_CITY_RANGE_ADAPT', 1, 1, -1, 50);

INSERT INTO Language_en_US (Tag, Text)
VALUES
('TXT_KEY_BUILDING_WR_CITY_RANGE_ADAPT', 'White Room City Ranged Adaptation');
