-- ============================================================================
-- White Room Kid Kiyotaka - Adaptation Dummy Promotions
-- ============================================================================
--
-- Foundation file for later Lua scaling.
--
-- Lua should store exact adaptation points, then apply only the highest matching
-- tier from each track:
--   WR_KIYOTAKA_COMBAT_ADAPTATION_*      -> offensive/general combat scaling
--   WR_KIYOTAKA_RESISTANCE_ADAPTATION_*  -> damage resistance scaling
--   WR_KIYOTAKA_ATTACK_ADAPTATION_*      -> attack-only scaling
--   WR_KIYOTAKA_DESPERATION_ADAPTATION_* -> strength while below 50 HP
--   WR_KIYOTAKA_VS_<UNITCOMBAT>_*        -> class-specific kill adaptation
--
-- Threshold plan:
--   I   = 1 point
--   II  = 5 points
--   III = 10 points
--   IV  = 20 points
--   V   = 35 points
--   VI  = 50 points
--   VII = 75 points
--   VIII= 100 points
-- ============================================================================

INSERT INTO UnitPromotions
    (Type, Description, Help, Sound, CannotBeChosen, LostWithUpgrade, CombatPercent)
VALUES
    ('PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_I',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_I',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_I_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 1),

    ('PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_II',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_II',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_II_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 5),

    ('PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_III',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_III',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_III_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 10),

    ('PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_IV',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_IV',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_IV_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 20),

    ('PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_V',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_V',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_V_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 35),

    ('PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_VI',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_VI',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_VI_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 50),

    ('PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_VII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_VII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_VII_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 75),

    ('PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_VIII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_VIII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_VIII_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 100);

INSERT INTO UnitPromotions
    (Type, Description, Help, Sound, CannotBeChosen, LostWithUpgrade, DefenseMod, RangedDefenseMod)
VALUES
    ('PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_I',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_I',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_I_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 1, 1),

    ('PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_II',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_II',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_II_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 5, 5),

    ('PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_III',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_III',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_III_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 10, 10),

    ('PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_IV',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_IV',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_IV_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 20, 20),

    ('PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_V',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_V',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_V_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 35, 35),

    ('PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_VI',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_VI',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_VI_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 50, 50),

    ('PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_VII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_VII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_VII_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 75, 75),

    ('PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_VIII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_VIII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_VIII_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 100, 100);

INSERT INTO UnitPromotions
    (Type, Description, Help, Sound, CannotBeChosen, LostWithUpgrade)
VALUES
    ('PROMOTION_WR_PERFECT_ADAPTATION',
     'TXT_KEY_PROMOTION_WR_PERFECT_ADAPTATION',
     'TXT_KEY_PROMOTION_WR_PERFECT_ADAPTATION_HELP',
     'AS2D_IF_LEVELUP', 1, 0);

INSERT INTO UnitPromotions
    (Type, Description, Help, Sound, CannotBeChosen, LostWithUpgrade, AttackMod)
VALUES
    ('PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_I',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_I',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_I_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 1),
    ('PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_II',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_II',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_II_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 5),
    ('PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_III',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_III',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_III_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 10),
    ('PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_IV',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_IV',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_IV_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 20),
    ('PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_V',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_V',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_V_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 35),
    ('PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_VI',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_VI',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_VI_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 50),
    ('PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_VII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_VII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_VII_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 75),
    ('PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_VIII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_VIII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_VIII_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 100);

INSERT INTO UnitPromotions
    (Type, Description, Help, Sound, CannotBeChosen, LostWithUpgrade, CombatPercent)
VALUES
    ('PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_I',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_I',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_I_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 1),
    ('PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_II',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_II',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_II_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 5),
    ('PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_III',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_III',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_III_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 10),
    ('PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_IV',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_IV',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_IV_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 20),
    ('PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_V',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_V',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_V_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 35),
    ('PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_VI',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_VI',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_VI_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 50),
    ('PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_VII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_VII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_VII_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 75),
    ('PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_VIII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_VIII',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_VIII_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 100);

INSERT INTO UnitPromotions
    (Type, Description, Help, Sound, CannotBeChosen, LostWithUpgrade, CanMoveAfterAttacking)
VALUES
    ('PROMOTION_WR_KIYOTAKA_FLOW_STATE',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_FLOW_STATE',
     'TXT_KEY_PROMOTION_WR_KIYOTAKA_FLOW_STATE_HELP',
     'AS2D_IF_LEVELUP', 1, 0, 1);

INSERT INTO UnitPromotions
    (Type, Description, Help, Sound, CannotBeChosen, LostWithUpgrade)
SELECT
    'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_I',
    'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_I',
    'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_I_HELP',
    'AS2D_IF_LEVELUP', 1, 0
FROM UnitCombatInfos
UNION ALL
SELECT 'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_II',
       'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_II',
       'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_II_HELP',
       'AS2D_IF_LEVELUP', 1, 0 FROM UnitCombatInfos
UNION ALL
SELECT 'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_III',
       'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_III',
       'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_III_HELP',
       'AS2D_IF_LEVELUP', 1, 0 FROM UnitCombatInfos
UNION ALL
SELECT 'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_IV',
       'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_IV',
       'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_IV_HELP',
       'AS2D_IF_LEVELUP', 1, 0 FROM UnitCombatInfos
UNION ALL
SELECT 'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_V',
       'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_V',
       'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_V_HELP',
       'AS2D_IF_LEVELUP', 1, 0 FROM UnitCombatInfos
UNION ALL
SELECT 'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VI',
       'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VI',
       'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VI_HELP',
       'AS2D_IF_LEVELUP', 1, 0 FROM UnitCombatInfos
UNION ALL
SELECT 'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VII',
       'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VII',
       'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VII_HELP',
       'AS2D_IF_LEVELUP', 1, 0 FROM UnitCombatInfos
UNION ALL
SELECT 'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VIII',
       'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VIII',
       'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VIII_HELP',
       'AS2D_IF_LEVELUP', 1, 0 FROM UnitCombatInfos;

INSERT INTO UnitPromotions_UnitCombatMods (PromotionType, UnitCombatType, Modifier)
SELECT 'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_I', Type, 1 FROM UnitCombatInfos
UNION ALL SELECT 'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_II', Type, 5 FROM UnitCombatInfos
UNION ALL SELECT 'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_III', Type, 10 FROM UnitCombatInfos
UNION ALL SELECT 'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_IV', Type, 20 FROM UnitCombatInfos
UNION ALL SELECT 'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_V', Type, 35 FROM UnitCombatInfos
UNION ALL SELECT 'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VI', Type, 50 FROM UnitCombatInfos
UNION ALL SELECT 'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VII', Type, 75 FROM UnitCombatInfos
UNION ALL SELECT 'PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VIII', Type, 100 FROM UnitCombatInfos;

INSERT INTO Unit_FreePromotions (UnitType, PromotionType)
VALUES ('UNIT_WR_KIYOTAKA', 'PROMOTION_WR_PERFECT_ADAPTATION');

INSERT INTO Language_en_US (Tag, Text)
VALUES
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_I', 'Combat Adaptation I'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_I_HELP', '+1% Combat Strength.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_II', 'Combat Adaptation II'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_II_HELP', '+5% Combat Strength.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_III', 'Combat Adaptation III'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_III_HELP', '+10% Combat Strength.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_IV', 'Combat Adaptation IV'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_IV_HELP', '+20% Combat Strength.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_V', 'Combat Adaptation V'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_V_HELP', '+35% Combat Strength.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_VI', 'Combat Adaptation VI'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_VI_HELP', '+50% Combat Strength.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_VII', 'Combat Adaptation VII'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_VII_HELP', '+75% Combat Strength.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_VIII', 'Combat Adaptation VIII'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_COMBAT_ADAPTATION_VIII_HELP', '+100% Combat Strength.'),

    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_I', 'Resistance Adaptation I'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_I_HELP', '+1% Defense and Ranged Defense.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_II', 'Resistance Adaptation II'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_II_HELP', '+5% Defense and Ranged Defense.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_III', 'Resistance Adaptation III'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_III_HELP', '+10% Defense and Ranged Defense.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_IV', 'Resistance Adaptation IV'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_IV_HELP', '+20% Defense and Ranged Defense.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_V', 'Resistance Adaptation V'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_V_HELP', '+35% Defense and Ranged Defense.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_VI', 'Resistance Adaptation VI'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_VI_HELP', '+50% Defense and Ranged Defense.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_VII', 'Resistance Adaptation VII'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_VII_HELP', '+75% Defense and Ranged Defense.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_VIII', 'Resistance Adaptation VIII'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_RESISTANCE_ADAPTATION_VIII_HELP', '+100% Defense and Ranged Defense.');

INSERT INTO Language_en_US (Tag, Text)
VALUES
    ('TXT_KEY_PROMOTION_WR_PERFECT_ADAPTATION', 'Perfect Adaptation'),
    ('TXT_KEY_PROMOTION_WR_PERFECT_ADAPTATION_HELP', 'Permanently improves from kills, damage dealt, damage taken, and surviving near failure.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_I', 'Attack Adaptation I'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_I_HELP', '+1% Attack Strength.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_II', 'Attack Adaptation II'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_II_HELP', '+5% Attack Strength.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_III', 'Attack Adaptation III'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_III_HELP', '+10% Attack Strength.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_IV', 'Attack Adaptation IV'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_IV_HELP', '+20% Attack Strength.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_V', 'Attack Adaptation V'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_V_HELP', '+35% Attack Strength.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_VI', 'Attack Adaptation VI'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_VI_HELP', '+50% Attack Strength.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_VII', 'Attack Adaptation VII'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_VII_HELP', '+75% Attack Strength.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_VIII', 'Attack Adaptation VIII'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_ATTACK_ADAPTATION_VIII_HELP', '+100% Attack Strength.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_I', 'Desperation Adaptation I'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_I_HELP', '+1% Combat Strength while below 50 HP.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_II', 'Desperation Adaptation II'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_II_HELP', '+5% Combat Strength while below 50 HP.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_III', 'Desperation Adaptation III'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_III_HELP', '+10% Combat Strength while below 50 HP.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_IV', 'Desperation Adaptation IV'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_IV_HELP', '+20% Combat Strength while below 50 HP.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_V', 'Desperation Adaptation V'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_V_HELP', '+35% Combat Strength while below 50 HP.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_VI', 'Desperation Adaptation VI'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_VI_HELP', '+50% Combat Strength while below 50 HP.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_VII', 'Desperation Adaptation VII'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_VII_HELP', '+75% Combat Strength while below 50 HP.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_VIII', 'Desperation Adaptation VIII'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_DESPERATION_ADAPTATION_VIII_HELP', '+100% Combat Strength while below 50 HP.'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_FLOW_STATE', 'Flow State'),
    ('TXT_KEY_PROMOTION_WR_KIYOTAKA_FLOW_STATE_HELP', 'May move after attacking once Perfect Adaptation movement chance reaches 100%.');

INSERT INTO Language_en_US (Tag, Text)
SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_I',
       'Class Adaptation I' FROM UnitCombatInfos
UNION ALL SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_I_HELP',
       '+1% Combat Strength against this unit combat class.' FROM UnitCombatInfos
UNION ALL SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_II',
       'Class Adaptation II' FROM UnitCombatInfos
UNION ALL SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_II_HELP',
       '+5% Combat Strength against this unit combat class.' FROM UnitCombatInfos
UNION ALL SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_III',
       'Class Adaptation III' FROM UnitCombatInfos
UNION ALL SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_III_HELP',
       '+10% Combat Strength against this unit combat class.' FROM UnitCombatInfos
UNION ALL SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_IV',
       'Class Adaptation IV' FROM UnitCombatInfos
UNION ALL SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_IV_HELP',
       '+20% Combat Strength against this unit combat class.' FROM UnitCombatInfos
UNION ALL SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_V',
       'Class Adaptation V' FROM UnitCombatInfos
UNION ALL SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_V_HELP',
       '+35% Combat Strength against this unit combat class.' FROM UnitCombatInfos
UNION ALL SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VI',
       'Class Adaptation VI' FROM UnitCombatInfos
UNION ALL SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VI_HELP',
       '+50% Combat Strength against this unit combat class.' FROM UnitCombatInfos
UNION ALL SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VII',
       'Class Adaptation VII' FROM UnitCombatInfos
UNION ALL SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VII_HELP',
       '+75% Combat Strength against this unit combat class.' FROM UnitCombatInfos
UNION ALL SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VIII',
       'Class Adaptation VIII' FROM UnitCombatInfos
UNION ALL SELECT 'TXT_KEY_PROMOTION_WR_KIYOTAKA_VS_' || substr(Type, 12) || '_VIII_HELP',
       '+100% Combat Strength against this unit combat class.' FROM UnitCombatInfos;
