-- White Room Kid Kiyotaka - City HP-loss adaptation dummy buildings
-- Invisible per-city buildings applied by Lua when White Room cities survive damage.

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description)
VALUES
('BUILDINGCLASS_WR_CITY_DEF_ADAPT_1',  'BUILDING_WR_CITY_DEF_ADAPT_1',  'TXT_KEY_BUILDING_WR_CITY_DEF_ADAPT'),
('BUILDINGCLASS_WR_CITY_DEF_ADAPT_5',  'BUILDING_WR_CITY_DEF_ADAPT_5',  'TXT_KEY_BUILDING_WR_CITY_DEF_ADAPT'),
('BUILDINGCLASS_WR_CITY_DEF_ADAPT_10', 'BUILDING_WR_CITY_DEF_ADAPT_10', 'TXT_KEY_BUILDING_WR_CITY_DEF_ADAPT'),
('BUILDINGCLASS_WR_CITY_DEF_ADAPT_25', 'BUILDING_WR_CITY_DEF_ADAPT_25', 'TXT_KEY_BUILDING_WR_CITY_DEF_ADAPT'),
('BUILDINGCLASS_WR_CITY_DEF_ADAPT_50', 'BUILDING_WR_CITY_DEF_ADAPT_50', 'TXT_KEY_BUILDING_WR_CITY_DEF_ADAPT');

INSERT INTO Buildings
    (Type, BuildingClass, Cost, FaithCost, PrereqTech, Description, NeverCapture,
     NukeImmune, HurryCostModifier, Defense, ExtraCityHitPoints)
VALUES
('BUILDING_WR_CITY_DEF_ADAPT_1',  'BUILDINGCLASS_WR_CITY_DEF_ADAPT_1',  -1, -1, NULL, 'TXT_KEY_BUILDING_WR_CITY_DEF_ADAPT', 1, 1, -1, 100,  1),
('BUILDING_WR_CITY_DEF_ADAPT_5',  'BUILDINGCLASS_WR_CITY_DEF_ADAPT_5',  -1, -1, NULL, 'TXT_KEY_BUILDING_WR_CITY_DEF_ADAPT', 1, 1, -1, 500,  5),
('BUILDING_WR_CITY_DEF_ADAPT_10', 'BUILDINGCLASS_WR_CITY_DEF_ADAPT_10', -1, -1, NULL, 'TXT_KEY_BUILDING_WR_CITY_DEF_ADAPT', 1, 1, -1, 1000, 10),
('BUILDING_WR_CITY_DEF_ADAPT_25', 'BUILDINGCLASS_WR_CITY_DEF_ADAPT_25', -1, -1, NULL, 'TXT_KEY_BUILDING_WR_CITY_DEF_ADAPT', 1, 1, -1, 2500, 25),
('BUILDING_WR_CITY_DEF_ADAPT_50', 'BUILDINGCLASS_WR_CITY_DEF_ADAPT_50', -1, -1, NULL, 'TXT_KEY_BUILDING_WR_CITY_DEF_ADAPT', 1, 1, -1, 5000, 50);

INSERT INTO Language_en_US (Tag, Text)
VALUES
('TXT_KEY_BUILDING_WR_CITY_DEF_ADAPT', 'White Room City Defense Adaptation');
